- hosts: localhost
  become: true
  gather_facts: true
  vars:
    ansible_become_password: "{{ localhost_become_password }}"
    venv_path: /opt/netapp_ansible
  tasks:
    - name: Install Python 3
      package:
        name: python3

    - name: Install virtualenv
      pip:
        name: virtualenv
        executable: pip3

    - name: Make venv Directory
      shell: |
        virtualenv {{ venv_path }}
      args:
        creates: "{{ venv_path }}"
      environment: 
            PATH: "{{ ansible_env.PATH}}:/sbin:/usr/sbin"
    - name: Install ansible
      pip:
        virtualenv: "{{ venv_path }}"
        name: ansible
        version: "{{ ansible_version }}"
        umask: "0022"
